package com.retoday.core.domain.recap.component

enum class ImagePolicyType {
    IMAGE_01_LEARNING_TOP,
    IMAGE_02_SHOPPING_TOP,
    IMAGE_03_GAME_TOP,
    IMAGE_04_CONTENT_TOP,
    IMAGE_05_COMMUNITY_TOP,
    IMAGE_06_NEWS_TOP,
    IMAGE_07_FINANCE_TOP,
    IMAGE_08_LIFE_TOP,
    IMAGE_09_SURFING_TOP,
    IMAGE_10_DESIGN_TOP,
    IMAGE_11_DEVELOPMENT_TOP,
    IMAGE_12_SCREEN_TIME_OVER_12H,
    IMAGE_13_SCREEN_TIME_UNDER_1H,
    IMAGE_14_CATEGORY_OVER_5,
    IMAGE_15_CATEGORY_ONLY_1,
    IMAGE_16_START_AFTER_9PM,
    IMAGE_17_START_BEFORE_9AM,
    IMAGE_18_RANDOM_1,
    IMAGE_19_RANDOM_2,
    IMAGE_20_RANDOM_3
}
