spring:
  application:
    name: recap-api
  main:
    banner-mode: off
  profiles:
    include:
    - core
  web:
    resources:
      add-mappings: false
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod
