spring:
  application:
    name: retoday-api
  main:
    banner-mode: off
  profiles:
    include:
    - auth
    - db
  web:
    resources:
      add-mappings: true
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
logging:
  config: classpath:log4j2-${spring.profiles.active}.yaml
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    groups-order: desc
    operations-sorter: method
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: false
