spring:
  application:
    name: retoday-api
  main:
    banner-mode: off
  profiles:
    include:
    - auth
    - db
  web:
    resources:
      add-mappings: false
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
logging:
  config: classpath:log4j2-${spring.profiles.active}.yaml
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod
