spring:
  jpa:
    open-in-view: false
datasource:
  main:
    driver-class-name: com.mysql.cj.jdbc.Driver
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  data:
    redis:
      url: redis://localhost:6379
datasource:
  main:
    jdbc-url: jdbc:mysql://localhost:3306/retoday
    username: root
    password: root
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
  data:
    redis:
      url: ${REDIS_URL}
datasource:
  main:
    jdbc-url: ${MAIN_DB_URL}
    username: ${MAIN_DB_USERNAME}
    password: ${MAIN_DB_PASSWORD}
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      url: ${REDIS_URL}
datasource:
  main:
    jdbc-url: ${MAIN_DB_URL}
    username: ${MAIN_DB_USERNAME}
    password: ${MAIN_DB_PASSWORD}
