name: Deploy to Prod

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets:
      SERVER_HOST: ${{ secrets.PROD_SERVER_HOST }}
      SERVER_PASSWORD: ${{ secrets.PROD_SERVER_PASSWORD }}
